### PR TITLE
Relax sprockets dependency

### PR DESCRIPTION
**Pull request by fojas**
The changes in Sprockets 3 don't seem like enough to make this not work.

### CODE REVIEW

**Comment by petebrowne** [comment]
This project uses [Appraisals](https://github.com/petebrowne/sprockets-plugin/blob/master/Appraisals) for testing compatibility with Sprockets. Can you add Sprockets 3.x and verify it actually passes the tests?

**Comment by fojas** [comment]
I have added the gemfiles for Sprockets 3.0 and 3.1.

**Comment by petebrowne** [comment]
Thanks!

**Comment by petebrowne** [comment]
Release [0.3.0](https://rubygems.org/gems/sprockets-plugin/versions/0.3.0)

**Pull request merged**
